[env]
ANTHROPIC_BASE_URL = "https://openrouter.ai/api"
ANTHROPIC_API_KEY = ""
ANTHROPIC_DEFAULT_SONNET_MODEL = "z-ai/glm-4.7"
ANTHROPIC_DEFAULT_OPUS_MODEL="deepseek/deepseek-v3.2"
ANTHROPIC_DEFAULT_HAIKU_MODEL="z-ai/glm-4.7-flash"
